spring.application.name=health-manager
# 数据库连接配置
spring.datasource.url=jdbc:mysql://localhost:3306/health_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=Cyx200803

# MyBatis 配置
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.health.entity

# 日志配置（方便调试）
logging.level.com.health.mapper=debug
logging.level.org.springframework.web=info